program: train.py
method: bayes
metric:
  goal: maximize
  name: final_val_acc
parameters:
  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  weight_decay:
    values: [0, 0.0001, 0.001]
  dropout:
    values: [0.2, 0.25, 0.3]
  batch_size:
    values: [64, 128, 256]
  epochs:
    value: 50
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 50
